export enum ChatEvent {
  MESSAGE_CREATE = 'MESSAGE_CREATE',
  MESSAGE_UPDATE = 'MESSAGE_UPDATE',
  MESSAGE_DELETE = 'MESSAGE_DELETE',
  REACTION_ADD = 'REACTION_ADD',
  REACTION_REMOVE = 'REACTION_REMOVE',
  MEMBER_JOIN = 'MEMBER_JOIN',
  MEMBER_LEAVE = 'MEMBER_LEAVE',
  TYPING_START = 'TYPING_START',
  TYPING_STOP = 'TYPING_STOP',
  PRESENCE_UPDATE = 'PRESENCE_UPDATE'
}

export type WSMessage<T = any> = {
  type: ChatEvent | string;
  payload?: T;
  meta?: any;
};
